### ISSUE TITLE
"Linux is a kernel"

### ISSUE THREAD

**Issue by davidak** [islinuxabout/islinuxabout.github.io#6]
I somehow came to this page and have the feeling that the communication style is not very constructive.

>>Is Linux About X?

>No. Linux is a kernel

That answer is kind of in a know-it-all manner. As if you want to feel better by showing that you know some technical detail about linux distros.

For people who actually don't know that and might not care (audience for elementary OS?), it could feel elitist. (You want to use linux, but don't even know what linux actually is???)

For people who know that linux is the kernel used in linux distributions, it might be just annoying to hear that over and over again.

When people say, "linux is about X", they don't mean the kernel, they actually mean "linux distributions are about X" and i guess you know that?

Maybe add one paragraph to the page if you think it's important to know and not just a funfact or implementation detail.

>Linux is actually just the kernel used in linux distributions. That's the only thing they all have in common. Most use also GNU tools, but not all (Android, Alpine). The come with different desktop environment or none at all, for example for servers.

But does for example an elementary OS user need to know about the technical details of the OS? Does a Windows user have to know the name of the kernel (it's just "Windows NT kernel") or command line tools? I guess the answer is No.

Maybe try to find a better way to spread your message. Be more specific if you are afraid you are misunderstood. People often do say "i use linux" when they mean "i use a linux distribution", probably just because it's shorten. Don't waste your time with fighting for this minor detail. Fight for user freedom by creating an alternative to proprietary software! (i know you do that)

**Comment by cassidyjames** [comment]
The target of this site is not elementary users, but typically other folks within the "desktop Linux" community. It's mostly just used as a home for some quick, oft-repeated answers instead of re-typing them each time.

**Comment by davidak** [comment]
ok. what do you think about my point that people that say "i use linux" actually mean "i use a linux distro". they don't refer to the kernel, what you claim here, but to the platform/operating system. you could say GNU/Linux

**Comment by cassidyjames** [comment]
I think this has been addressed in fb2a276a7f9cfc5d853435d75a44ab1ad4500076

**Comment by davidak** [comment]
You use the term "Linux-based operating systems" instead of "linux distribution". Do you think we all should do that?
